name: ChatManager
version: ${project.version}
main: jp.yama2211.chatManager.Main
api-version: '1.21'
authors: [ yamagami2211 ]
website: https://yama2211.jp/
commands:
  channel:
    description: チャンネル管理コマンド
    usage: /channel <サブコマンド>
    aliases: [ch]
  global:
    description: 全体チャットにメッセージを送信します
    usage: /global [メッセージ]
    aliases: [g]